#shop
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      name: backend-ecshop4
  replicas: 2
  template:
    metadata:
      labels:
        name: backend-ecshop4
    spec:
      volumes:
        - name: web-data
          hostPath:
            path: /home/ubuntu/deploy/php-server/www/
        - name: nginx-host
          hostPath:
            path: /home/ubuntu/deploy/nginx-server/nginx_conf/
      containers:
        - name: nginx
          image: deploy_nginx-server:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: web-data
              mountPath: /var/www/
            - name: nginx-host
              mountPath: /etc/nginx/
          ports:
            - containerPort: 80
            - containerPort: 8000
        - name: php7
          image: deploy_php-server:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: web-data
              mountPath: /var/www/
          ports:
            - containerPort: 9000
---

apiVersion: v1
kind: Service
metadata:
  name: web-svc
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: nginx-service-1
    - port: 8000   #service暴露在cluster ip上的端口，通过<cluster ip>:port访问服务,通过此端口集群内的服务可以相互访问
      targetPort: 8000  #Pod的外部访问端口，port和nodePort的数据通过这个端口进入到Pod内部，Pod里面的containers的端口映射到这个端口，提供服务
      #nodePort: 30001 #Node节点的端口，<nodeIP>:nodePort 是提供给集群外部客户访问service的入口
      protocol: TCP
      name: nginx-service-2
    - port: 443
      targetPort: 443
      protocol: TCP
      name: nginx-service-3
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: php-service
  selector:
    name: backend-ecshop4

